const CORPUS = new Map([
  ["125dhcc", {abbr:"1,25-DHCC",full:"1,25-dihydroxy cholecalciferol"}],
  ["aas", {abbr:"AAS",full:"Atomic Absorption Spectroscopy"}],
  ["aoac", {abbr:"AOAC",full:"Association of Official Analytical Chemists"}],
  ["apci", {abbr:"APCI",full:"Atmospheric Pressure Chemical Ionization"}],
  ["bmr", {abbr:"BMR",full:"Basal metabolic rate"}],
  ["boaa", {abbr:"BOAA",full:"Oxalyldiaminopropionic acid"}],
  ["bv", {abbr:"BV",full:"Biological Value"}],
  ["cal", {abbr:"Cal",full:"Calories"}],
  ["cbc", {abbr:"CBC",full:"Cation binding capacity"}],
  ["cf", {abbr:"CF",full:"Crude fibre"}],
  ["cftri", {abbr:"CFTRI",full:"Central Food Technological Research Institute"}],
  ["chd", {abbr:"CHD",full:"Coronary heart disease"}],
  ["cho", {abbr:"CHO",full:"Carbohydrate"}],
  ["crm", {abbr:"CRM",full:"Certified Reference Material"}],
  ["cu", {abbr:"CU",full:"Consumption units"}],
  ["df", {abbr:"DF",full:"Dietary fibre"}],
  ["dna", {abbr:"DNA",full:"Deoxyribonucleic acid"}],
  ["dri", {abbr:"DRI",full:"Dietary reference intake"}],
  ["eaa", {abbr:"EAA",full:"Essential Amino Acids"}],
  ["efa", {abbr:"EFA",full:"Essential fatty acids"}],
  ["esi", {abbr:"ESI",full:"Electro Spray Ionization"}],
  ["fao", {abbr:"FAO",full:"Food and Agriculture Organization of the United Nations"}],
  ["faostat", {abbr:"FAOSTAT",full:"Food and Agriculture Organization Statistics"}],
  ["fct", {abbr:"FCT",full:"Food Composition Tables"}],
  ["gc", {abbr:"GC",full:"Gas Chromatography"}],
  ["gi", {abbr:"GI",full:"Gastrointestinal"}],
  ["glv", {abbr:"GLV",full:"Green Leafy Vegetables"}],
  ["hplc", {abbr:"HPLC",full:"High Performance Liquid Chromatography"}],
  ["icds", {abbr:"ICDS",full:"Integrated Child Development Services"}],
  ["icmr", {abbr:"ICMR",full:"Indian Council of Medical Research"}],
  ["icpms", {abbr:"ICP-MS",full:"Inductively Coupled Plasma Mass Spectrometry"}],
  ["ida", {abbr:"IDA",full:"Iron Deficiency Anemia"}],
  ["idd", {abbr:"IDD",full:"Iodine deficiency disorders"}],
  ["idf", {abbr:"IDF",full:"Insoluble Dietary Fibre"}],
  ["ifct", {abbr:"IFCT",full:"Indian Food Composition Tables"}],
  ["infoods", {abbr:"INFOODS",full:"International Network of Food Data Systems"}],
  ["ip6", {abbr:"IP-6",full:"Inositol hexaphosphate"}],
  ["irfa", {abbr:"IRFA",full:"Indian Research Fund Association"}],
  ["iu", {abbr:"IU",full:"International Units"}],
  ["kcal", {abbr:"Kcal",full:"Kilo calories"}],
  ["kj", {abbr:"kJ",full:"kilo Joule"}],
  ["n", {abbr:"N",full:"Normality"}],
  ["nac", {abbr:"NAC",full:"Nutritional Advisory Committee"}],
  ["ndo", {abbr:"NDO",full:"Non-digestible oligosaccharides"}],
  ["nfhs", {abbr:"NFHS",full:"National Family Health Survey"}],
  ["niddm", {abbr:"NIDDM",full:"Non-insulin dependent diabetes mellitus"}],
  ["nin", {abbr:"NIN",full:"National Institute of Nutrition"}],
  ["nnmb", {abbr:"NNMB",full:"National Nutrition Monitoring Bureau"}],
  ["npu", {abbr:"NPU",full:"Net protein utilized"}],
  ["nrfa", {abbr:"NRFA",full:"Nutrition Research Funds Association"}],
  ["nrl", {abbr:"NRL",full:"Nutrition Research Laboratories"}],
  ["nvif", {abbr:"NVIF",full:"Nutritive Value of Indian Foods"}],
  ["pem", {abbr:"PEM",full:"Protein Energy Malnutrition"}],
  ["per", {abbr:"PER",full:"Protein Efficiency Ratio"}],
  ["pufa", {abbr:"PUFA",full:"Polyunsaturated Fatty Acids"}],
  ["qaqc", {abbr:"QAQC",full:"Quality assurance and quality control"}],
  ["rae", {abbr:"RAE",full:"Retinol equivalent activity"}],
  ["rda", {abbr:"RDA",full:"Recommended dietary allowances"}],
  ["rdi", {abbr:"RDI",full:"Recommended dietary intakes"}],
  ["rid", {abbr:"RID",full:"Refractive index detector"}],
  ["rp", {abbr:"RP",full:"Reversed phase"}],
  ["rpo", {abbr:"RPO",full:"Red palm oil"}],
  ["rpv", {abbr:"RPV",full:"Relative protein value"}],
  ["scfa", {abbr:"SCFA",full:"Short chain fatty acids"}],
  ["sd", {abbr:"SD",full:"Standard deviation"}],
  ["sdf", {abbr:"SDF",full:"Soluble Dietary Fibre"}],
  ["tdf", {abbr:"TDF",full:"Total Dietary Fibre"}],
  ["usa", {abbr:"USA",full:"United States of America"}],
  ["unu", {abbr:"UNU",full:"United Nations University"}],
  ["ut", {abbr:"UT",full:"Union territory"}],
  ["uv", {abbr:"UV",full:"Ultra violet"}],
  ["vad", {abbr:"VAD",full:"Vitamin A deficiency"}],
  ["whc", {abbr:"WHC",full:"Water holding capacity"}],
  ["who", {abbr:"WHO",full:"World Health Organization"}],
]);
module.exports = CORPUS;
