const CORPUS = new Map([
  ["a", {abbr:"A.",full:"Assamese"}],
  ["aas", {abbr:"AAS",full:"Atomic Absorption Spectroscopy"}],
  ["aoac", {abbr:"AOAC",full:"Association of Official Analytical Chemists"}],
  ["apci", {abbr:"APCI",full:"Atmospheric Pressure Chemical Ionization"}],
  ["b", {abbr:"B.",full:"Bengali"}],
  ["bv", {abbr:"BV",full:"Biological Value"}],
  ["cftri", {abbr:"CFTRI",full:"Central Food Technological Research Institute"}],
  ["cho", {abbr:"CHO",full:"Carbohydrate"}],
  ["common", {abbr:"Common",full:"Common name"}],
  ["crm", {abbr:"CRM",full:"Certified Reference Material"}],
  ["dri", {abbr:"DRI",full:"Dietary reference intake"}],
  ["eaa", {abbr:"EAA",full:"Essential Amino Acids"}],
  ["esi", {abbr:"ESI",full:"Electro Spray Ionization"}],
  ["fao", {abbr:"FAO",full:"Food and Agriculture Organization of the United Nations"}],
  ["faostat", {abbr:"FAOSTAT",full:"Food and Agriculture Organization Statistics"}],
  ["fct", {abbr:"FCT",full:"Food Composition Tables"}],
  ["g", {abbr:"G.",full:"Gujarati"}],
  ["gc", {abbr:"GC",full:"Gas Chromatography"}],
  ["glvs", {abbr:"GLVs",full:"Green Leafy Vegetables"}],
  ["h", {abbr:"H.",full:"Hindi"}],
  ["hplc", {abbr:"HPLC",full:"High Performance Liquid Chromatography"}],
  ["icmr", {abbr:"ICMR",full:"Indian Council of Medical Research"}],
  ["icpms", {abbr:"ICP-MS",full:"Inductively Coupled Plasma Mass Spectrometry"}],
  ["ida", {abbr:"IDA",full:"Iron Deficiency Anemia"}],
  ["idf", {abbr:"IDF",full:"International Diabetes Federation"}],
  ["ifct", {abbr:"IFCT",full:"Indian Food Composition Tables"}],
  ["infoods", {abbr:"INFOODS",full:"International Network of Food Data Systems"}],
  ["ip6", {abbr:"IP-6",full:"Inositol hexaphosphate"}],
  ["irfa", {abbr:"IRFA",full:"Indian Research Fund Association"}],
  ["iu", {abbr:"IU",full:"International Units"}],
  ["kan", {abbr:"Kan.",full:"Kannada"}],
  ["kash", {abbr:"Kash.",full:"Kashmiri"}],
  ["kh", {abbr:"Kh.",full:"Khasi"}],
  ["kj", {abbr:"kJ",full:"kilo Joule"}],
  ["kon", {abbr:"Kon.",full:"Konkani"}],
  ["m", {abbr:"M.",full:"Manipuri"}],
  ["mal", {abbr:"Mal.",full:"Malayalam"}],
  ["mar", {abbr:"Mar.",full:"Marathi"}],
  ["n", {abbr:"N.",full:"Nepali"}],
  ["nac", {abbr:"NAC",full:"Nutritional Advisory Committee"}],
  ["ndo", {abbr:"NDO",full:"Non-digestible oligosaccharides"}],
  ["nfhs", {abbr:"NFHS",full:"National Family Health Survey"}],
  ["nin", {abbr:"NIN",full:"National Institute of Nutrition"}],
  ["nnmb", {abbr:"NNMB",full:"National Nutrition Monitoring Bureau"}],
  ["nrfa", {abbr:"NRFA",full:"Nutrition Research Funds Association"}],
  ["nrl", {abbr:"NRL",full:"Nutrition Research Laboratories"}],
  ["nvif", {abbr:"NVIF",full:"Nutritive Value of Indian Foods"}],
  ["o", {abbr:"O.",full:"Oriya"}],
  ["p", {abbr:"P.",full:"Punjabi"}],
  ["pem", {abbr:"PEM",full:"Protein Energy Malnutrition"}],
  ["per", {abbr:"PER",full:"Protein Efficiency Ratio"}],
  ["psus", {abbr:"PSUs",full:"Primary Sampling Units"}],
  ["pufa", {abbr:"PUFA",full:"Polyunsaturated Fatty Acids"}],
  ["qaqc", {abbr:"QAQC",full:"Quality assurance and quality control"}],
  ["rae", {abbr:"RAE",full:"Retinol equivalent activity"}],
  ["rid", {abbr:"RID",full:"Refractive index detector"}],
  ["rp", {abbr:"RP",full:"Reversed phase"}],
  ["s", {abbr:"S.",full:"Sanskrit"}],
  ["sci", {abbr:"Sci.",full:"Scientific name"}],
  ["sd", {abbr:"SD",full:"Standard deviation"}],
  ["sdf", {abbr:"SDF",full:"Soluble Dietary Fibre"}],
  ["ssus", {abbr:"SSUs",full:"Secondary sampling units"}],
  ["tam", {abbr:"Tam.",full:"Tamil"}],
  ["tdf", {abbr:"TDF",full:"Total Dietary Fibre"}],
  ["tel", {abbr:"Tel.",full:"Telugu"}],
  ["u", {abbr:"U.",full:"Urdu"}],
  ["ut", {abbr:"UT",full:"Union territory"}],
  ["uv", {abbr:"UV",full:"Ultra violet"}],
  ["vad", {abbr:"VAD",full:"Vitamin A deficiency"}],
  ["who", {abbr:"WHO",full:"World Health Organization"}],
]);
module.exports = CORPUS;
